Repository Ducky-Chickens/bangazon-API-sprint1, pull requests merged in 2018-03, with the labels that each got.

#19 setup basic file structure and example js files where needed for naming convention
  .gitignore
  README.md
  build-data.js
  build-db.js
  data/example.json
  databases/computers.js
  generators/computer-faker.js
  package-lock.json
  package.json
Labels: good first issue

#21 computers faker data generator and database builder features finished
  build-data.js
  build-db.js
  data/computers.json
  databases/computers.js
  generators/computer-faker.js
  package.json
Labels: enhancement

#22 Dh create departments
  build-data.js
  build-db.js
  data/departments.json
  databases/departments.js
  generators/departments-faker.js
Labels: enhancement

#36 Dh create employees
  build-db.js
  data/computers.json
  data/customers.json
  data/departments.json
  data/employees.json
  data/training-programs.json
  databases/departments.js
  databases/employees.js
  generators/departments-faker.js
  generators/employees-faker.js
Labels: requirement

#33 finished table build and faker data for payment types
  app.js
  build-db.js
  data/payment-types.json
  databases/computers.js
  databases/employees.js
  databases/payment-types.js
  generators/employees-faker.js
  generators/payment-type-faker.js
Labels: requirement

#37 Vf create products
  build-db.js
  data/products.json
  databases/products.js
  generators/product-faker.js
Labels: requirement

#42 Hp prod type
  .gitignore
  app.js
  controllers/programs-ctrl.js
  data/computers.json
  data/customers.json
  models/Training-programs.js
  package.json
  routes/index.js
  routes/programs-route.js
Labels: help wanted

#44 successful employee_trainingPgrm table build
  build-db.js
  data/emp_training.json
  databases/employee_trainingPgrm.js
  generators/emp_train-faker.js
Labels: requirement

#46 Dh departments get post put
  .gitignore
  controllers/departments-ctrl.js
  databases/departments.js
  models/Departments.js
  routes/computers-route.js
  routes/departments-route.js
  routes/index.js
Labels: enhancement

#47 Finished Computers GET PUT POST DELETE
  controllers/computers-ctrl.js
  models/Computers.js
  routes/computers-route.js
Labels: completed feature

#48 delete programs
  controllers/programs-ctrl.js
  data/training-programs.json
  models/Training-programs.js
  routes/index.js
  routes/programs-route.js
Labels: completed feature

#50 Dh departments get post put
  controllers/departments-ctrl.js
  models/Departments.js
  routes/departments-route.js
  routes/index.js
Labels: completed feature, enhancement

#52 Dh employee methods
  controllers/employees-ctrl.js
  models/Employees.js
  routes/employees-route.js
  routes/index.js
Labels: completed feature

#51 Hp prod type access
  controllers/product-type-ctrl.js
  controllers/programs-ctrl.js
  models/Product-types.js
  routes/index.js
  routes/prodTypes-route.js
  routes/programs-route.js
Labels: completed feature

#59 Add product information when selecting single order
  controllers/orders-ctrl.js
  data/orders.json
  databases/orders.js
  generators/order-faker.js
  models/Order.js
Labels: completed feature

#61 created readme for employees, departments, libraries and contributors
  README.md
  controllers/departments-ctrl.js
  controllers/employees-ctrl.js
  models/Department.js
  models/Employee.js
  routes/departments-route.js
  routes/employees-route.js
Labels: completed feature

#67 prodType,program patch, readMe
  README.md
  controllers/product-type-ctrl.js
  controllers/programs-ctrl.js
  models/Product-type.js
  models/Training-program.js
  routes/index.js
  routes/product-types-route.js
  routes/programs-route.js
Labels: invalid
